platform: linux

image_resource:
  type: docker-image
  privileged: true
  source: {repository: maven, tag: 3.3.9-jdk-8}

inputs:
  - name: spring-boot-concourse

outputs:
  - name: build-output

run:
  path: "spring-boot-concourse/tasks/build.sh"